"""Modif

Revision ID: 1007e98123d8
Revises: d56bb52cb888
Create Date: 2020-01-08 13:50:17.187155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1007e98123d8'
down_revision = 'd56bb52cb888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contract_ids', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'contracts', ['contract_ids'], ['address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'contract_ids')
    # ### end Alembic commands ###
