"""Add state enum column

Revision ID: c7d895370a6e
Revises: 0585c4f1dcd8
Create Date: 2020-01-11 17:51:43.231057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d895370a6e'
down_revision = '0585c4f1dcd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('state', sa.Enum('in_progress', 'done', name='state_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'state')
    # ### end Alembic commands ###
